matrix:
- name: Markdown
  aspell:
    lang: de
    d: de_CH
  dictionary:
    wordlists:
    - .github/wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - 'content/**/*.md'
  default_encoding: utf-8
