title: EMBAG-Check
description: Ist deine Organisation EMBAG-ready?
share_image: http://smartcity.ebp.ch/user/themes/smart-city/images/Tool-Open-Data-Plattform.JPG
collections:
  - sections
  - contacts
exclude:
  - README.md