theme: jekyll-theme-leap-day
title: EMBAG-Check
description: Ist deine Organisation EMBAG-ready?
show_downloads: false
share_image: http://smartcity.ebp.ch/user/themes/smart-city/images/Tool-Open-Data-Plattform.JPG
exclude:
  - README.md