title: EMBAG-Check | EBP Schweiz
description: Ist deine Organisation EMBAG-ready?
share_image: https://ebp-group.github.io/embag-check/assets/images/bundeshaus_klein.png
collections:
  - sections
  - contacts
exclude:
  - README.md