title: EMBAG-Check | EBP
description: Ist Ihre Organisation EMBAG-ready?
share_image: https://ebp-group.github.io/embag-check/assets/images/bundeshaus_klein.png
collections_dir: content
collections:
  - contacts
  - sections
  - org
  - tech
  - ogd
  - api
  - oss
exclude:
  - README.md
