theme: jekyll-theme-leap-day
title: EMBAG-Check
description: Ist deine Organisation EMBAG-ready?
show_downloads: false
share_image: http://smartcity.ebp.ch/user/themes/smart-city/images/Tool-Open-Data-Plattform.JPG
lead_text: Das [Bundesgesetz über den Einsatz elektronischer Mittel zur Erfüllung von Behördenaufgaben (EMBAG)](https://www.fedlex.admin.ch/eli/fga/2023/787/de) ist ein Gesetz, welches verschiedene Aspekte der Digitalisierung adressiert. Es geht u.a. die Veröffentlichung von Open Government Data (OGD) und Open Source Software (OSS), den Einsatz von Schnittstellen (APIs) und Standards.
