title: EMBAG-Check | EBP
description: Ist Ihre Organisation EMBAG-ready?
share_image: https://embag-check.ch/assets/images/bundeshaus_klein.jpeg
collections_dir: content
collections:
  - contacts
  - sections
  - org
  - tech
  - ogd
  - api
  - oss
exclude:
  - README.md
